categories: [Metabolomics]
description: '[W4M][Metabolomics][LC-MS][GC-MS][NMR] Transforms the dataMatrix intensity values.'
homepage_url: http://workflow4metabolomics.org
long_description: 'The module currently currently performs log2(1+X) and log10(1+X), where X is the data matrix (missing values remain at "NA").'
name: transformation
owner: ethevenot
remote_repository_url: https://github.com/workflow4metabolomics/transformation.git
